apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
spec:
  selector:
    matchLabels:
      run: my-app
  replicas: 2
  template:
    metadata:
      labels:
        run: my-app
    spec:
      containers:
      - name: my-app
        image: 10.0.1.150:5000/sjjeon/argocd-deploy:104
        ports:
        - containerPort: 80
